updating file structure to match production repo

diff --git a/.github/workflows/parsegithubissue.yaml b/.github/workflows/parsegithubissue.yaml
--- a/.github/workflows/parsegithubissue.yaml
+++ b/.github/workflows/parsegithubissue.yaml
@@ -29,7 +29,16 @@ jobs:
         uses: actions-ecosystem/action-add-labels@v1
         with:
           labels: "Processing"
-      
+
+      - name: Remove labels
+        uses: actions-ecosystem/action-remove-labels@v1
+        if: env.PROCESS_SUCCESS == 'false'
+        with:
+          labels: |
+            Success
+            Error in form
+            High Cost
+
       - name: Checkout
         uses: actions/checkout@v3
         with:
@@ -66,11 +75,11 @@ jobs:
       - name: Install requests
         run: |
           pip3 install requests
-                    
+
       - name: process form data
         continue-on-error: true
         run: |
-          python file_handling.py
+          python ./scripts/file_handling.py
 
       - name: Create Issue Comment
         if: env.PROCESS_SUCCESS != 'true'
@@ -81,28 +90,6 @@ jobs:
             ${{ env.ISSUE_COMMENT }}
             Please edit this issue and select "Update comment" to resubmit.
 
-      - name: Remove labels
-        uses: actions-ecosystem/action-remove-labels@v1
-        if: env.PROCESS_SUCCESS == 'false'
-        with:
-          labels: |
-            Processing
-            Success
-            
-      - name: Add error label
-        if: env.PROCESS_SUCCESS == 'false'
-        uses: actions-ecosystem/action-add-labels@v1
-        with:
-          labels: "Error in form"
-          
-      - name: Remove error labels
-        uses: actions-ecosystem/action-remove-labels@v1
-        if: env.PROCESS_SUCCESS == 'true'
-        with:
-          labels: |
-            Error in form
-            Processing
-
       - name: 'Az CLI login'
         uses: azure/login@v1
         with:
@@ -112,13 +99,13 @@ jobs:
       - name: get aks resource details
         if: env.PROCESS_SUCCESS == 'true'
         continue-on-error: true
-        run: ./scripts/aks-resource-details.sh
+        run: ./scripts/aks/resource-details.sh
 
       - name: process costs
         if: env.PROCESS_SUCCESS == 'true'
         continue-on-error: true
         run: |
-          python cost-calculator.py
+          python ./scripts/cost-calculator.py || echo "Calculating cost failed"
 
       - name: Add cost details as a comment
         if: env.PROCESS_SUCCESS == 'true'
@@ -134,11 +121,33 @@ jobs:
         with:
           labels: "High Cost"
 
+      - name: Remove error labels
+        uses: actions-ecosystem/action-remove-labels@v1
+        if: env.PROCESS_SUCCESS == 'true'
+        with:
+          labels: |
+            Error in form
+            Processing
+
+      - name: Remove labels
+        uses: actions-ecosystem/action-remove-labels@v1
+        if: env.PROCESS_SUCCESS == 'false'
+        with:
+          labels: |
+            Processing
+            Success
+
       - name: Add success label
         if: env.PROCESS_SUCCESS == 'true'
         uses: actions-ecosystem/action-add-labels@v1
         with:
           labels: "Success"
+
+      - name: Add error label
+        if: env.PROCESS_SUCCESS != 'true'
+        uses: actions-ecosystem/action-add-labels@v1
+        with:
+          labels: "Error in form"
 
       - name: Commit to master
         if: env.PROCESS_SUCCESS == 'true'
